max_num_iterations: 30001
spatial_lr_scale: 3

optimizers:
  means:
    optimizer:
      lr: "${eval: 1.6e-4 * ${spatial_lr_scale}}"
    scheduler:
      lr_final: "${eval: 1.6e-6 * ${spatial_lr_scale}}"
      max_steps: "${eval: ${max_num_iterations} - 1}"
  features_dc:
    optimizer:
      lr: 0.0025
  features_rest:
    optimizer:
      lr: "${eval: 0.0025 / 20}"
  opacities:
    optimizer:
      lr: 0.05
  scales:
    optimizer:
      lr: 0.001
  quats:
    optimizer:
      lr: 0.001

pipeline:
  model:
    warmup_length: 500
    cull_alpha_thresh: 0.04
    cull_scale_thresh: 0.08
    densify_grad_thresh: 0.002
    densify_size_thresh: 0.01
    cull_screen_size: 0.14
    split_screen_size: 0.05
    stop_screen_size_at: 4000
    random_init: False
    num_random: 10000
    random_scale: 8.0
    stop_split_at: "${eval: ${max_num_iterations} - 5000}"

vis: tensorboard
viewer:
  websocket-port: 7006
