logging:
  local_writer:
    max_log_size: 0
  max_buffer_size: 20
  steps_per_log: 10

machine:
  seed: 42
  
mixed_precision: false
output_dir: outputs
steps_per_eval_batch: 500
steps_per_eval_image: 2000
steps_per_save: 2000

pipeline:
  datamanager:
    train_cameras_sampling_strategy: random
    train_cameras_sampling_seed: 42
    cache_images: gpu

dataparser:
  scale_factor: 1.0
  alpha_color: white
