max_num_iterations: 40001

optimizers:
  means:
    optimizer:
      lr: "${eval: 1.6e-4 * 5}"
    scheduler:
      lr_final: "${eval: 1.6e-6 * 5}"
      max_steps: "${eval: ${max_num_iterations} - 1}"
  features_dc:
    optimizer:
      lr: 0.0025
  features_rest:
    optimizer:
      lr: "${eval: 0.0025 / 20}"
  opacities:
    optimizer:
      lr: 0.05
  scales:
    optimizer:
      lr: 0.001
  quats:
    optimizer:
      lr: 0.001
  deform:
    optimizer:
      lr: "${eval: 1.6e-4 * 5}"
    scheduler:
      warmup_steps: 3000
      lr_final: "${eval: 1.6e-5 * 5}"
      max_steps: "${eval: ${max_num_iterations} - 1}"

pipeline:
  model:
    warm_up: 3000
    refine_start: 500
    refine_every: 100
    resolution_schedule: 3000
    background_color: white
    num_downscales: 2
    cull_alpha_thresh: 0.05
    cull_scale_thresh: 0.1
    continue_cull_post_densification: True
    reset_alpha_every: 30
    densify_grad_thresh: 0.0012
    densify_size_thresh: 0.01
    n_split_samples: 2
    sh_degree_interval: 1000
    cull_screen_size: 0.15
    split_screen_size: 0.05
    stop_screen_size_at: 4000
    random_init: False
    num_random: 10000
    random_scale: 10.0
    ssim_lambda: 0.2
    stop_split_at: 15000
    sh_degree: 3
    use_scale_regularization: False
    max_gauss_ratio: 10.0
    output_depth_during_training: False
    rasterize_mode: classic
    use_bilateral_grid: False
    grid_shape: [16, 16, 8]
    color_corrected_metrics: False
    # deform:
    #   net_width: 64
    #   timebase_pe: 4
    #   defor_depth: 1
    #   posebase_pe: 10
    #   scale_rotation_pe: 2
    #   opacity_pe: 2
    #   timenet_width: 64
    #   timenet_output: 32
    #   bounds: 1.6
    #   grid_pe: 0
    #   static_mlp: False
    #   apply_rotation: False
    #   no_dx: False
    #   no_grid: False
    #   no_ds: False
    #   no_dr: False
    #   no_do: True
    #   no_dshs: True
    #   empty_voxel: False
    #
vis: viewer+tensorboard
viewer:
  websocket-port: 8008
